version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
      - image: circleci/postgres:9.6.5-alpine-ram
    environment:
      DATABASE_URL: postgresql://root@localhost/circle_test
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-{{ checksum "package-lock.json" }}
            - npm-deps-
      - run:
          name: Update NPM
          command: sudo npm i -g npm@latest
      - run:
          name: Install Dependencies
          command: npm i
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Lint
          command: npm run lint --output-file ./reports/eslint.xml
          when: always
      - run:
          name: Test
          command: npm run test
          when: always
      - codecov/upload:
          name: Upload Coverage to Codecov
          file: ./coverage/lcov.info
          conf: ""
workflows:
  version: 2
  testing:
    jobs:
      - build