name: Publish Module

on:
  release:
    types:
      - created

jobs:
  build:
    name: Publish

    strategy:
      matrix:
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1.4.2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}