name: Quality Assurance

on:
  push:
  pull_request:

jobs:
  test:
    name: Ava Testing

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]
        bun: [1.0.4]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun }}
      - name: Install Dependencies
        run: bun i
      - name: Run Tests
        run: bun run test
      - name: Upload Coverage
        if: success()
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageLocations: ${{ github.workspace }}/coverage/lcov.info:lcov
  lint:
    name: Linting

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]
        bun: [1.0.4]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun }}
      - name: Install Dependencies
        run: bun i
      - name: Validate Typescript
        uses: fersilva16/ts-report-action@1.2.1
      - name: Lint Code
        run: bun run lint
