name: Testing

on: 
  push:
    branches:
      - '*'
      - '!gh-pages'
  pull_request:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@latest
      - name: Set up Node
        uses: actions/setup-node@latest
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependencies
        uses: actions/cache@latest
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm i
      - name: Run Tests
        run: npm test
      - name: Upload Coverage
        uses: codecov/codecov-action@latest
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage/lcov.info
        
